### ISSUE TITLE
make wonderland doesn't work

### ISSUE THREAD

**Issue by trotter** [auser/alice#1]
Running "make wonderland" attempts to pull from the private wonderland repo, not the public one. I'd love to submit a patch here (it's an easy fix), but I'm not really sure how. Also, I don't feel like forking and issuing a pull request for something so simple :-)

**Comment by hungryblank** [comment]
the patch that was meant to fix this bug contains another bug
the path of wonderland repo is wrong a ":" is in place of a /.
check here for a fixed Makefile version
http://gist.github.com/148729

**Comment by auser** [comment]
This fix is pushed. Also fixed the emakefile problem as well in the latest 2 pushes.
