### ISSUE TITLE
Alice start script

### ISSUE THREAD

**Issue by mikev** [auser/alice#11]
The init.d scripts require a standard method to start Alice.  Since multiple RabbitMQ brokers can be started on different ports, we also need to be able to start multiple Alice instances on different ports.

For example:

alice.sh start -n dev@myhost.com -port 9001 -log /var/log/alice
alice.sh start -n test@myhost.com -port 9002 -log /var/log/alice

Log files should not overlap, similar to the RabbitMQ logs

**Comment by auser** [comment]
Added ./scripts/alice.sh 

Pass -h for help to see the list of available options
