### ISSUE TITLE
Alice multiple logs

### ISSUE THREAD

**Issue by mikev** [auser/alice#14]
Currently the alice log is named "alice.log".  This creates a problem, when or if, multiple Alice instances are running.  Ideally Alice will name its log files similar to RabbitMQ.

For example:

alice@dev@myhost.com.log

**Comment by auser** [comment]
I believe this works already...

**Comment by mikev** [comment]
Yes, but it could work better.  RabbitMQ logs are stored in the format <broker>@<hostname>.log.  This is always unique, especially with multiple host machines.  Alice logs are stored in the format alice.<port number>.log.

The RabbitMQ format prevents namespace collisions between different hosts.  This is especially important when log files are aggregated to a central location.

Alice should do something similar.

**Comment by mikev** [comment]
Hmmm, github just munged my comment

RabbitMQ format: broker@hostname.log
Alice format: alice.port.log

RabbitMQ format is better.

**Comment by auser** [comment]
I added this in the last push.

**Comment by mikev** [comment]
Cool, thanks!
