### ISSUE TITLE
Error durring make boot

### ISSUE THREAD

**Issue by slider** [auser/alice#19]
After not finding the bootfile:

$ ./start.sh 
(cd ebin; erl -pa ebin -noshell -run make_boot write_scripts alice)
{"init terminating in do_boot",{undef,[{make_boot,write_scripts,[["alice"]]},{init,start_it,1},{init,start_em,1}]}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
make: **\* [boot] Error 1
{"init terminating in do_boot",{'cannot get bootfile','alice.boot'}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()

I tried creating it as suggested in the Common Problems but ran into:

$ make boot
(cd ebin; erl -pa ebin -noshell -run make_boot write_scripts alice)
{"init terminating in do_boot",{undef,[{make_boot,write_scripts,[["alice"]]},{init,start_it,1},{init,start_em,1}]}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
make: **\* [boot] Error 1

Any hints whats going wrong?

**Comment by yuvipanda** [comment]
Am running into the same problem (Ubuntu Karmic). Any solution found?

**Comment by mirven** [comment]
Me too on CentOS and OSX.

**Comment by auser** [comment]
Ah sorry, I missed these comments entirely.

How did you install erlang? Did you:

```
apt-get install erlang-dev
```

It looks like your version of erlang doesn't have make... How did you install erlang?

**Comment by skippy** [comment]
I ran into the same issue, and I used macports:
   port install erlang

I looked around but didn't see anything for erlang-dev.  Is there a way to see if erlang-make is installed or not?  (sorry, total nub when it comes to erlang)

  port install gmake

to

**Comment by auser** [comment]
What version of erlang do you have?

erl -version

**Comment by paukul** [comment]
same problem for me: 
codeslave :: erlang/alice » erl -version
Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 5.7.2

codeslave :: erlang/alice » sudo ./start.sh  
(cd ebin; erl -pa ebin -noshell -run make_boot write_scripts alice)
{"init terminating in do_boot",{undef,[{make_boot,write_scripts,[["alice"]]},{init,start_it,1},{init,start_em,1}]}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
make: **\* [boot] Error 1
{"init terminating in do_boot",{'cannot get bootfile','alice.boot'}}

**Comment by auser** [comment]
Try pulling... and you have to type "make" before any of the files are made paukul. I added 'make' into the start.sh file

**Comment by paukul** [comment]
@auser great! thanks a lot. works like a charm!

**Comment by skippy** [comment]
@auser, sorry, no luck!  shoot.

running 'make' or './start.sh' from a fresh install produced the same error (it is really long and repetitive), but the specifics seem to be:

*\* Reason for termination == 
*\* {{badmatch,{error,{fread,input}}},
    [{memsup,get_memory_usage,1},{memsup,'-handle_info/2-fun-0-',2}]}

=ERROR REPORT==== 16-Nov-2009::13:28:34 ===
Error in process <0.50.0> on node 'alice@myComputer.local' with exit value: {{badmatch,{error,{fread,input}}},[{memsup,get_memory_usage,1},{memsup,'-handle_info/2-fun-0-',2}]}

**Comment by auser** [comment]
That error is resulting from the output of vm_stat

What does your vm_stat look like:

```
vm_stat
```

**Comment by skippy** [comment]
hi Auser,

it looks good:
http://gist.github.com/236468

it's interesting, one time it ran and failed with a different error, I think, around the cookie.  So I used the -setcookie, as macports installs the rabbitmq cookie at /opt/local/var/lib/rabbitmq/.erlang.cookie.

out of curiosity, where is the default reference for the erlang cookie?  I scanned the source and didn't see it, though I know zip about erlang.

thanks Auser,
Adam

**Comment by auser** [comment]
It's in:
    ~/.erlang.cookie

no prob,
Ari

**Comment by paukul** [comment]
sorry, me again. running into the same problems again. This time on a Debian machine and the former solutions didn't help me.

rabbis:/virtual/alice# uname -a 
Linux rabbis 2.6.23.9-ibm-hs20 #1 SMP Fri Jan 18 15:28:27 CET 2008 x86_64 GNU/Linux

rabbis:/virtual/alice# erl -version
Erlang (ASYNC_THREADS) (BEAM) emulator version 5.5.2

rabbis:/virtual/alice# ./start.sh 
make[1]: Entering directory `/virtual/alice/deps/mochiweb'
(cd src;make all)
make[2]: Entering directory`/virtual/alice/deps/mochiweb/src'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory`/virtual/alice/deps/mochiweb/src'
make[1]: Leaving directory `/virtual/alice/deps/mochiweb'
(cd ebin; erl -pa ebin -noshell -run make_boot write_scripts alice)
write_scripts for "alice"
{"init terminating in do_boot",{undef,[{string,to_lower,["alice"]},{make_boot,write_scripts,1},{init,start_it,1},{init,start_em,1}]}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
make: **\* [boot] Error 1
{"init terminating in do_boot",{'cannot get bootfile','alice.boot'}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
rabbis:/virtual/alice#

-- pascal

**Comment by paukul** [comment]
ok seems like it's the erlang version

http://erlang.org/doc/apps/stdlib/part_notes_frame.html
functions to_lower and to_upper were added at version 1.15.2

**Comment by ducky427** [comment]
I seem to be getting the same problem as paukul [above](http://github.com/auser/alice/issues#issue/19/comment/76529). I am running RabbitMQ 1.7.0 on Ubuntu Server 9.10. I had erlang-dev installed and did 'make boot' before running start.sh. Version of erlang:

```
    Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 5.7.2
```

cheers

**Comment by francois** [comment]
Still the same problem, and nothing above helped:

```
francois:~$ sudo apt-get install erlang-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
erlang-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 8 not upgraded.

francois:~/alice$ git show | head -n 3 
commit 4cd949b60bfa5bdbad135769e303708f68740757
Author: Ari Lerner <arilerner@mac.com>
Date:   Mon Dec 7 13:54:56 2009 -0800

francois@localhost:~/alice$ uname -a
Linux localhost 2.6.32-linode23 #1 SMP Sat Dec 5 16:04:55 UTC 2009 i686 GNU/Linux

francois:~/alice$ erl -version
Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 5.7.2

francois:~/alice$ make boot 
(cd ebin; erl -pa ebin -noshell -run make_boot write_scripts alice)
{"init terminating in do_boot",{undef,[{make_boot,write_scripts,[["alice"]]},{init,start_it,1},{init,start_em,1}]}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
make: *** [boot] Error 1
```

**Comment by auser** [comment]
Did you:

```
make 
```

first?

**Comment by francois** [comment]
I did

```
francois:~/alice$ make
make[1]: Entering directory `/home/francois/alice/deps/mochiweb'
(cd src;make all)
make[2]: Entering directory `/home/francois/alice/deps/mochiweb/src'
erlc -W -I ../include  +debug_info -o ../ebin mochifmt.erl
erlc -W -I ../include  +debug_info -o ../ebin mochifmt_records.erl
erlc -W -I ../include  +debug_info -o ../ebin mochifmt_std.erl
erlc -W -I ../include  +debug_info -o ../ebin mochihex.erl
erlc -W -I ../include  +debug_info -o ../ebin mochijson.erl
erlc -W -I ../include  +debug_info -o ../ebin mochijson2.erl
erlc -W -I ../include  +debug_info -o ../ebin mochinum.erl
erlc -W -I ../include  +debug_info -o ../ebin mochiweb.erl
erlc -W -I ../include  +debug_info -o ../ebin mochiweb_app.erl
erlc -W -I ../include  +debug_info -o ../ebin mochiweb_charref.erl
erlc -W -I ../include  +debug_info -o ../ebin mochiweb_cookies.erl
erlc -W -I ../include  +debug_info -o ../ebin mochiweb_echo.erl
erlc -W -I ../include  +debug_info -o ../ebin mochiweb_headers.erl
erlc -W -I ../include  +debug_info -o ../ebin mochiweb_html.erl
erlc -W -I ../include  +debug_info -o ../ebin mochiweb_http.erl
erlc -W -I ../include  +debug_info -o ../ebin mochiweb_multipart.erl
erlc -W -I ../include  +debug_info -o ../ebin mochiweb_request.erl
erlc -W -I ../include  +debug_info -o ../ebin mochiweb_response.erl
erlc -W -I ../include  +debug_info -o ../ebin mochiweb_skel.erl
erlc -W -I ../include  +debug_info -o ../ebin mochiweb_socket_server.erl
erlc -W -I ../include  +debug_info -o ../ebin mochiweb_sup.erl
erlc -W -I ../include  +debug_info -o ../ebin mochiweb_util.erl
erlc -W -I ../include  +debug_info -o ../ebin reloader.erl
make[2]: Leaving directory `/home/francois/alice/deps/mochiweb/src'
make[1]: Leaving directory `/home/francois/alice/deps/mochiweb'
{"init terminating in do_boot",{undef,[{make,all,[]},{erl_eval,do_apply,5},{erl_eval,expr,5},{init,start_it,1},{init,start_em,1}]}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
make: *** [compile] Error 1
francois:~/alice$ make boot
(cd ebin; erl -pa ebin -noshell -run make_boot write_scripts alice)
{"init terminating in do_boot",{undef,[{make_boot,write_scripts,[["alice"]]},{init,start_it,1},{init,start_em,1}]}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
make: *** [boot] Error 1
francois:~/alice$ ./start.sh
make[1]: Entering directory `/home/francois/alice/deps/mochiweb'
(cd src;make all)
make[2]: Entering directory `/home/francois/alice/deps/mochiweb/src'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/francois/alice/deps/mochiweb/src'
make[1]: Leaving directory `/home/francois/alice/deps/mochiweb'
{"init terminating in do_boot",{undef,[{make,all,[]},{erl_eval,do_apply,5},{erl_eval,expr,5},{init,start_it,1},{init,start_em,1}]}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
make: *** [compile] Error 1
./start.sh: 6: [[: not found
{"init terminating in do_boot",{'cannot get bootfile','alice.boot'}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
```

**Comment by auser** [comment]
Try pulling the latest push.
I can't replicate this problem... yet

**Comment by francois** [comment]
Still no go...

```
francois:~/alice$ make clean
rm -rf ebin/*.beam ebin/erl_crash.dump erl_crash.dump ebin/*.boot ebin/*.rel ebin/*.script 

francois:~/alice$ make
make[1]: Entering directory `/home/francois/alice/deps/mochiweb'
(cd src;make all)
make[2]: Entering directory `/home/francois/alice/deps/mochiweb/src'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/francois/alice/deps/mochiweb/src'
make[1]: Leaving directory `/home/francois/alice/deps/mochiweb'
{"init terminating in do_boot",{undef,[{make,all,[]},{erl_eval,do_apply,5},{erl_eval,expr,5},{init,start_it,1},{init,start_em,1}]}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
make: *** [compile] Error 1
```

I'm francois.beausoleil@gmail.com if you want to chat.

**Comment by francois** [comment]
Finally found what the problem was: the universe APT repository was commented out in /etc/apt/sources.list.  Once I enabled them and apt-get install erlang-src erlang-tools, I was good to go!

**Comment by auser** [comment]
Glad to be of help :)

**Comment by kwloafman** [comment]
Hi,

I'm getting the same thing, I think.  Below is my complete install, make, and start attempt.  I'm on Karmic with Universe enabled.  All the erlang-\* packages are installed, but something is still not working.  Any help would be appreciated.

...Thanks,
...Ken

ken@stealth:~/workspace$ rm -rf alice/
ken@stealth:~/workspace$ git clone git://github.com/auser/alice.git
Initialized empty Git repository in /home/ken/workspace/alice/.git/
remote: Counting objects: 1368, done.
remote: Compressing objects: 100% (956/956), done.
remote: Total 1368 (delta 614), reused 883 (delta 355)
Receiving objects: 100% (1368/1368), 460.17 KiB, done.
Resolving deltas: 100% (614/614), done.
ken@stealth:~/workspace$ cd alice/
ken@stealth:~/workspace/alice$ make
make[1]: Entering directory `/home/ken/workspace/alice/deps/mochiweb'
(cd src;make all)
make[2]: Entering directory`/home/ken/workspace/alice/deps/mochiweb/src'
erlc -W -I ../include  +debug_info -o ../ebin mochifmt.erl
erlc -W -I ../include  +debug_info -o ../ebin mochifmt_records.erl
erlc -W -I ../include  +debug_info -o ../ebin mochifmt_std.erl
erlc -W -I ../include  +debug_info -o ../ebin mochihex.erl
erlc -W -I ../include  +debug_info -o ../ebin mochijson2.erl
erlc -W -I ../include  +debug_info -o ../ebin mochijson.erl
erlc -W -I ../include  +debug_info -o ../ebin mochinum.erl
erlc -W -I ../include  +debug_info -o ../ebin mochiweb_app.erl
erlc -W -I ../include  +debug_info -o ../ebin mochiweb_charref.erl
erlc -W -I ../include  +debug_info -o ../ebin mochiweb_cookies.erl
erlc -W -I ../include  +debug_info -o ../ebin mochiweb_echo.erl
erlc -W -I ../include  +debug_info -o ../ebin mochiweb.erl
erlc -W -I ../include  +debug_info -o ../ebin mochiweb_headers.erl
erlc -W -I ../include  +debug_info -o ../ebin mochiweb_html.erl
erlc -W -I ../include  +debug_info -o ../ebin mochiweb_http.erl
erlc -W -I ../include  +debug_info -o ../ebin mochiweb_multipart.erl
erlc -W -I ../include  +debug_info -o ../ebin mochiweb_request.erl
erlc -W -I ../include  +debug_info -o ../ebin mochiweb_response.erl
erlc -W -I ../include  +debug_info -o ../ebin mochiweb_skel.erl
erlc -W -I ../include  +debug_info -o ../ebin mochiweb_socket_server.erl
erlc -W -I ../include  +debug_info -o ../ebin mochiweb_sup.erl
erlc -W -I ../include  +debug_info -o ../ebin mochiweb_util.erl
erlc -W -I ../include  +debug_info -o ../ebin reloader.erl
make[2]: Leaving directory `/home/ken/workspace/alice/deps/mochiweb/src'
make[1]: Leaving directory`/home/ken/workspace/alice/deps/mochiweb'
Recompile: src/utils/utils
Recompile: src/utils/testing
Recompile: src/utils/rabint
Recompile: src/utils/make_boot
Recompile: src/utils/loudmouth
Recompile: src/utils/config
Recompile: src/rest/rest_server_sup
Recompile: src/rest/rest_server
Recompile: src/rest/rest_app
Recompile: src/alice/alice_sup
Recompile: src/alice/alice_log
Recompile: src/alice/alice_app
Recompile: src/rest/controllers/vhosts
Recompile: src/rest/controllers/version
Recompile: src/rest/controllers/users
Recompile: src/rest/controllers/template
Recompile: src/rest/controllers/system
Recompile: src/rest/controllers/queues
Recompile: src/rest/controllers/permissions
Recompile: src/rest/controllers/info
Recompile: src/rest/controllers/home
Recompile: src/rest/controllers/exchanges
Recompile: src/rest/controllers/dev
Recompile: src/rest/controllers/dashboard
Recompile: src/rest/controllers/control
Recompile: src/rest/controllers/conn
Recompile: src/rest/controllers/bindings
Recompile: src/rest/controllers/assets
ken@stealth:~/workspace/alice$ ./start.sh 
make[1]: Entering directory `/home/ken/workspace/alice/deps/mochiweb'
(cd src;make all)
make[2]: Entering directory`/home/ken/workspace/alice/deps/mochiweb/src'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory`/home/ken/workspace/alice/deps/mochiweb/src'
make[1]: Leaving directory `/home/ken/workspace/alice/deps/mochiweb'
(cd ebin; erl -pa deps/mochiweb/ebin -pa ebin -noshell -run make_boot write_scripts alice)
write_scripts for "alice"
Writing to "alice.rel" (as alice)
_WARNING_ kernel: Object code (application) out of date
_WARNING_ kernel: Object code (application_controller) out of date
_WARNING_ kernel: Object code (application_master) out of date
_WARNING_ kernel: Object code (application_starter) out of date
_WARNING_ kernel: Object code (auth) out of date
_WARNING_ kernel: Object code (code) out of date
_WARNING_ kernel: Object code (packages) out of date
_WARNING_ kernel: Object code (code_server) out of date
_WARNING_ kernel: Object code (dist_util) out of date
_WARNING_ kernel: Object code (erl_boot_server) out of date
_WARNING_ kernel: Object code (erl_distribution) out of date
_WARNING_ kernel: Object code (erl_reply) out of date
_WARNING_ kernel: Object code (error_handler) out of date
_WARNING_ kernel: Object code (error_logger) out of date
_WARNING_ kernel: Object code (file) out of date
_WARNING_ kernel: Object code (file_server) out of date
_WARNING_ kernel: Object code (file_io_server) out of date
_WARNING_ kernel: Object code (global) out of date
_WARNING_ kernel: Object code (global_group) out of date
_WARNING_ kernel: Object code (global_search) out of date
_WARNING_ kernel: Object code (group) out of date
_WARNING_ kernel: Object code (heart) out of date
_WARNING_ kernel: Object code (hipe_unified_loader) out of date
_WARNING_ kernel: Object code (inet6_tcp) out of date
_WARNING_ kernel: Object code (inet6_tcp_dist) out of date
_WARNING_ kernel: Object code (inet6_udp) out of date
_WARNING_ kernel: Object code (inet6_sctp) out of date
_WARNING_ kernel: Object code (inet_config) out of date
_WARNING_ kernel: Object code (inet_hosts) out of date
_WARNING_ kernel: Object code (inet_gethost_native) out of date
_WARNING_ kernel: Object code (inet_tcp_dist) out of date
_WARNING_ kernel: Object code (kernel) out of date
_WARNING_ kernel: Object code (kernel_config) out of date
_WARNING_ kernel: Object code (net) out of date
_WARNING_ kernel: Object code (net_adm) out of date
_WARNING_ kernel: Object code (net_kernel) out of date
_WARNING_ kernel: Object code (os) out of date
_WARNING_ kernel: Object code (ram_file) out of date
_WARNING_ kernel: Object code (rpc) out of date
_WARNING_ kernel: Object code (user) out of date
_WARNING_ kernel: Object code (user_drv) out of date
_WARNING_ kernel: Object code (user_sup) out of date
_WARNING_ kernel: Object code (disk_log) out of date
_WARNING_ kernel: Object code (disk_log_1) out of date
_WARNING_ kernel: Object code (disk_log_server) out of date
_WARNING_ kernel: Object code (disk_log_sup) out of date
_WARNING_ kernel: Object code (dist_ac) out of date
_WARNING_ kernel: Object code (erl_ddll) out of date
_WARNING_ kernel: Object code (erl_epmd) out of date
_WARNING_ kernel: Object code (erts_debug) out of date
_WARNING_ kernel: Object code (gen_tcp) out of date
_WARNING_ kernel: Object code (gen_udp) out of date
_WARNING_ kernel: Object code (gen_sctp) out of date
_WARNING_ kernel: Object code (inet) out of date
_WARNING_ kernel: Object code (inet_db) out of date
_WARNING_ kernel: Object code (inet_dns) out of date
_WARNING_ kernel: Object code (inet_parse) out of date
_WARNING_ kernel: Object code (inet_res) out of date
_WARNING_ kernel: Object code (inet_tcp) out of date
_WARNING_ kernel: Object code (inet_udp) out of date
_WARNING_ kernel: Object code (inet_sctp) out of date
_WARNING_ kernel: Object code (pg2) out of date
_WARNING_ kernel: Object code (seq_trace) out of date
_WARNING_ kernel: Object code (standard_error) out of date
_WARNING_ kernel: Object code (wrap_log_reader) out of date
_WARNING_ stdlib: Object code (array) out of date
_WARNING_ stdlib: Object code (base64) out of date
_WARNING_ stdlib: Object code (beam_lib) out of date
_WARNING_ stdlib: Object code (c) out of date
_WARNING_ stdlib: Object code (calendar) out of date
_WARNING_ stdlib: Object code (dets) out of date
_WARNING_ stdlib: Object code (dets_server) out of date
_WARNING_ stdlib: Object code (dets_sup) out of date
_WARNING_ stdlib: Object code (dets_utils) out of date
_WARNING_ stdlib: Object code (dets_v8) out of date
_WARNING_ stdlib: Object code (dets_v9) out of date
_WARNING_ stdlib: Object code (dict) out of date
_WARNING_ stdlib: Object code (digraph) out of date
_WARNING_ stdlib: Object code (digraph_utils) out of date
_WARNING_ stdlib: Object code (edlin) out of date
_WARNING_ stdlib: Object code (edlin_expand) out of date
_WARNING_ stdlib: Object code (epp) out of date
_WARNING_ stdlib: Object code (eval_bits) out of date
_WARNING_ stdlib: Object code (erl_bits) out of date
_WARNING_ stdlib: Object code (erl_compile) out of date
_WARNING_ stdlib: Object code (erl_eval) out of date
_WARNING_ stdlib: Object code (erl_expand_records) out of date
_WARNING_ stdlib: Object code (erl_internal) out of date
_WARNING_ stdlib: Object code (erl_lint) out of date
_WARNING_ stdlib: Object code (erl_parse) out of date
_WARNING_ stdlib: Object code (erl_posix_msg) out of date
_WARNING_ stdlib: Object code (erl_pp) out of date
_WARNING_ stdlib: Object code (erl_scan) out of date
_WARNING_ stdlib: Object code (erl_tar) out of date
_WARNING_ stdlib: Object code (error_logger_file_h) out of date
_WARNING_ stdlib: Object code (error_logger_tty_h) out of date
_WARNING_ stdlib: Object code (escript) out of date
_WARNING_ stdlib: Object code (ets) out of date
_WARNING_ stdlib: Object code (file_sorter) out of date
_WARNING_ stdlib: Object code (filelib) out of date
_WARNING_ stdlib: Object code (filename) out of date
_WARNING_ stdlib: Object code (gb_trees) out of date
_WARNING_ stdlib: Object code (gb_sets) out of date
_WARNING_ stdlib: Object code (gen) out of date
_WARNING_ stdlib: Object code (gen_event) out of date
_WARNING_ stdlib: Object code (gen_fsm) out of date
_WARNING_ stdlib: Object code (gen_server) out of date
_WARNING_ stdlib: Object code (io) out of date
_WARNING_ stdlib: Object code (io_lib) out of date
_WARNING_ stdlib: Object code (io_lib_format) out of date
_WARNING_ stdlib: Object code (io_lib_fread) out of date
_WARNING_ stdlib: Object code (io_lib_pretty) out of date
_WARNING_ stdlib: Object code (lib) out of date
_WARNING_ stdlib: Object code (lists) out of date
_WARNING_ stdlib: Object code (log_mf_h) out of date
_WARNING_ stdlib: Object code (math) out of date
_WARNING_ stdlib: Object code (ms_transform) out of date
_WARNING_ stdlib: Object code (orddict) out of date
_WARNING_ stdlib: Object code (ordsets) out of date
_WARNING_ stdlib: Object code (otp_internal) out of date
_WARNING_ stdlib: Object code (pg) out of date
_WARNING_ stdlib: Object code (pool) out of date
_WARNING_ stdlib: Object code (proc_lib) out of date
_WARNING_ stdlib: Object code (proplists) out of date
_WARNING_ stdlib: Object code (qlc) out of date
_WARNING_ stdlib: Object code (qlc_pt) out of date{error_logger,{{2010,5,12},{11,55,51}},"Can't set long node name!\nPlease check your configuration\n",[]}
{error_logger,{{2010,5,12},{11,55,51}},crash_report,[[{initial_call,{net_kernel,init,['Argument__1']}},{pid,<0.21.0>},{registered_name,[]},{error_info,{exit,{error,badarg},[{gen_server,init_it,6},{proc_lib,init_p_do_apply,3}]}},{ancestors,[net_sup,kernel_sup,<0.8.0>]},{messages,[]},{links,[<0.18.0>]},{dictionary,[{longnames,true}]},{trap_exit,true},{status,running},{heap_size,987},{stack_size,24},{reductions,871}],[]]}
{error_logger,{{2010,5,12},{11,55,51}},supervisor_report,[{supervisor,{local,net_sup}},{errorContext,start_error},{reason,{'EXIT',nodistribution}},{offender,[{pid,undefined},{name,net_kernel},{mfa,{net_kernel,start_link,[[alice,longnames]]}},{restart_type,permanent},{shutdown,2000},{child_type,worker}]}]}
{error_logger,{{2010,5,12},{11,55,51}},supervisor_report,[{supervisor,{local,kernel_sup}},{errorContext,start_error},{reason,shutdown},{offender,[{pid,undefined},{name,net_sup},{mfa,{erl_distribution,start_link,[]}},{restart_type,permanent},{shutdown,infinity},{child_type,supervisor}]}]}
{error_logger,{{2010,5,12},{11,55,51}},std_info,[{application,kernel},{exited,{shutdown,{kernel,start,[normal,[]]}}},{type,permanent}]}
{"Kernel pid terminated",application_controller,"{application_start_failure,kernel,{shutdown,{kernel,start,[normal,[]]}}}"}

Crash dump was written to: erl_crash.dump
Kernel pid terminated (application_controller) ({application_start_failure,kernel,{shutdown,{kernel,start,[normal,[]]}}})
ken@stealth:~/workspace/alice$
