### ISSUE TITLE
Document your build environment

### ISSUE THREAD

**Issue by hungryblank** [auser/alice#2]
It would be great if you could add in the Readme or on the wiki some docs about the environment setup to correctly compile the application.

Starting from a standard install of ubuntu it seems that it only compiles mochiweb but not anything related to alice

Here's the output, it seems is not picking up anything to compile in directory others than deps.
Feels like it's not finding make_boot but I'm new to erlang and I can't work out how to fix it.

<pre>
make[1]: Entering directory `/home/blank/personal/alice/deps/mochiweb'
(cd src;make all)
make[2]: Entering directory `/home/blank/personal/alice/deps/mochiweb/src'
erlc -W -I ../include  +debug_info -o ../ebin mochifmt.erl
erlc -W -I ../include  +debug_info -o ../ebin mochifmt_records.erl
erlc -W -I ../include  +debug_info -o ../ebin mochifmt_std.erl
erlc -W -I ../include  +debug_info -o ../ebin mochihex.erl
erlc -W -I ../include  +debug_info -o ../ebin mochijson2.erl
erlc -W -I ../include  +debug_info -o ../ebin mochijson.erl
erlc -W -I ../include  +debug_info -o ../ebin mochinum.erl
erlc -W -I ../include  +debug_info -o ../ebin mochiweb_app.erl
erlc -W -I ../include  +debug_info -o ../ebin mochiweb_charref.erl
erlc -W -I ../include  +debug_info -o ../ebin mochiweb_cookies.erl
erlc -W -I ../include  +debug_info -o ../ebin mochiweb_echo.erl
erlc -W -I ../include  +debug_info -o ../ebin mochiweb.erl
erlc -W -I ../include  +debug_info -o ../ebin mochiweb_headers.erl
erlc -W -I ../include  +debug_info -o ../ebin mochiweb_html.erl
erlc -W -I ../include  +debug_info -o ../ebin mochiweb_http.erl
erlc -W -I ../include  +debug_info -o ../ebin mochiweb_multipart.erl
erlc -W -I ../include  +debug_info -o ../ebin mochiweb_request.erl
erlc -W -I ../include  +debug_info -o ../ebin mochiweb_response.erl
erlc -W -I ../include  +debug_info -o ../ebin mochiweb_skel.erl
erlc -W -I ../include  +debug_info -o ../ebin mochiweb_socket_server.erl
erlc -W -I ../include  +debug_info -o ../ebin mochiweb_sup.erl
erlc -W -I ../include  +debug_info -o ../ebin mochiweb_util.erl
erlc -W -I ../include  +debug_info -o ../ebin reloader.erl
make[2]: Leaving directory `/home/blank/personal/alice/deps/mochiweb/src'
make[1]: Leaving directory `/home/blank/personal/alice/deps/mochiweb'
(cd ebin; erl -pa ebin -noshell -run make_boot write_scripts rest_app)
{"init terminating in do_boot",{undef,[{make_boot,write_scripts,[["rest_app"]]},{init,start_it,1},{init,start_em,1}]}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
make: *** [make_boot] Error 1
</pre>

**Comment by denik** [comment]
I have the same issue on debian unstable :(

**Comment by hungryblank** [comment]
fixed in the current master
