### ISSUE TITLE
Adding user hangs alice

### ISSUE THREAD

**Issue by n8gray** [auser/alice#3]
Alice hangs when I try adding a user with:
curl -i -XPOST -d'{"username":"n8gray", "password":"blah"}' http://locahost:9999/users

The "ebeam.smp" process starts taking 40% of my cpu and doesn't stop until I abort the alice process.  Nothing interesting comes up in the rabbitmq logs

I'm using OS X 10.5.7 on an Intel mac.  Some more version strings:
Erlang R13B01 (erts-5.7.2) [source] [smp:2:2] [rq:2] [async-threads:0] [kernel-poll:false]
RabbitMQ 1.6.0 (AMQP 8-0)
git head of alice (8aa4f43d32205229adcd326fce8f1a1eaf045211)

Thanks,
-n8

**Comment by auser** [comment]
Is this solved? Was this a local rabbitMQ error?

**Comment by n8gray** [comment]
I only resolved my other rabbitmq problems last night so I haven't had a chance to look at this yet.  I'll take another look today.

**Comment by auser** [comment]
Is this still an issue?

**Comment by n8gray** [comment]
I never got to the bottom of it.  I'm not going to have time to look at this in the near future so you should probably just close the issue.  Or hey, maybe I'll just push the "comment and close" button and see if that does it.
