### ISSUE TITLE
Make problems

### ISSUE THREAD

**Issue by cachedout** [auser/alice#4]
'make' produces several warnings:

[root@q1 auser-alice-581132a670c48be183fc34eec7e6ec6e44b7ac2c]# make

make[1]: Entering directory `/root/auser-alice-
581132a670c48be183fc34eec7e6ec6e44b7ac2c/deps/mochiweb'
(cd src;make all)

make[2]: Entering directory `/root/auser-alice-581132a670c48be183fc34eec7e6ec6e44b7ac2c/deps/mochiweb/src'

make[2]: Nothing to be done for `all'.

make[2]: Leaving directory `/root/auser-alice-581132a670c48be183fc34eec7e6ec6e44b7ac2c/deps/mochiweb/src'

make[1]: Leaving directory `/root/auser-alice-581132a670c48be183fc34eec7e6ec6e44b7ac2c/deps/mochiweb'
(cd ebin; erl -pa ebin -noshell -run make_boot write_scripts rest_app)
write_scripts for "rest_app"

Writing to "rest_app.rel" (as rest_app)

_WARNING_ rest_app: Source code not found: alice_log.erl

_WARNING_ rest_app: Source code not found: rest_app.erl

_WARNING_ rest_app: Source code not found: rest_server.erl

**Comment by auser** [comment]
Yup. These are known warnings... It still compiles and runs despite the warnings. We should definitely look at the warnings though. We'll keep this open 'til we can close the issues.

**Comment by nofxx** [comment]
I get a

```
 "Can't set long node name!\nPlease check your configuration\n
```

If I try the start, changed the line to alice@localhost, it starts but still some errors all around...

```
 ** System running to use fully qualified hostnames **
 ** Hostname localhost is illegal **
```

erlang R13B-2 / archlinux

**Comment by auser** [comment]
I'll have to make a more permanent fix for this, but...

try it with

 ./start.sh -sname alice

**Comment by nofxx** [comment]
Ahh very cool, works!
Thanks man.  Cool app =D

**Comment by auser** [comment]
Thanks!

Feel free to add, update UI, etc. Alice is pretty easy to get grips on (even if you don't know erlang) and Wonderland is almost just as easy. It's all javascript. If you are good at UI, that's one thing Wonderland could use.

Anyway, lemme know if I can help any more

**Comment by nofxx** [comment]
Hehe, yea, I've already discovered the 'web' folder ... hehe...
To be honest I'm looking for learn more about Erlang. To be more honest, I don't have time do eat this month... hehe
I'll try man. Thank you! =D

**Comment by nofxx** [comment]
Hey man, me again.. hehe, after pull start.sh says it can't find alice.boot, I've searched for a boot file (that's my erlang knowledge, sorry) and found 'rest_app'. Changed and it works again.. heh

**Comment by auser** [comment]
Done.
