### ISSUE TITLE
Small issue with 'make wonderland'

### ISSUE THREAD

**Issue by cachedout** [auser/alice#5]
This is a small issue but may affect some users.

In the event that a user does not have git installed on the system, typing 'make wonderland' will return an error:

[root@q1 auser-alice-8a1a9ffdfe19b95116f9ff9eb0c32a0ea2621b43]# make wonderland
[ -d web//wonderland ] || (mkdir web/ && cd web/ && git clone git://github.com/auser/wonderland.git)
/bin/sh: git: command not found

However, it will go ahead and create web/. This is a problem because the next time 'make wonderland' is run, it will error because web/ already exists:

[root@q1 auser-alice-8a1a9ffdfe19b95116f9ff9eb0c32a0ea2621b43]# make wonderland
[ -d web//wonderland ] || (mkdir web/ && cd web/ && git clone git://github.com/auser/wonderland.git)
mkdir: cannot create directory `web/': File exists
make: **\* [wonderland] Error 1

**Comment by auser** [comment]
Fixed and pushed
