### ISSUE TITLE
User UI feedback

### ISSUE THREAD

**Issue by mikev** [auser/alice#6]
On the Wonderland Users UI, we noticed the default behavior to delete a user, when the user is clicked, is a risky.  It will be too easy for a person, to accidentally click "OK".  What is probably better is if the click opens a window, with two options.  One option is to change the user's password, the other option is to delete the user.  Changing a user's password is probably a likely Admin task.

Same feedback applies to the VHost UI.

**Comment by auser** [comment]
I've updated the users/vhosts interface to include a double submit box as well as a change password front-end on Wonderland. Lemme know what you think.

**Comment by mikev** [comment]
Looks good.  Thanks!

**Comment by auser** [comment]
No prob!
