### ISSUE TITLE
Cannot find alice.boot

### ISSUE THREAD

**Issue by maniacmartin** [auser/alice#9]
I also got the message from start.sh about not being able to find alice.boot, which was mentioned in a comment on another ticket.
Can anyone explain in more detail how this can be fixed, as I have no Erlang knowledge?

**Comment by auser** [comment]
ManiacMartin,

Sure! type
    make boot

This is something I should push a fix too sooner, rather than later. Thanks!

Ari

**Comment by auser** [comment]
Did it work?

**Comment by maniacmartin** [comment]
Alas not, I got
 make boot
(cd ebin; erl -pa ebin -noshell -run make_boot write_scripts alice)
{"init terminating in do_boot",{undef,[{make_boot,write_scripts,[["alice"]]},{init,start_it,1},{init,start_em,1}]}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
make: **\* [boot] Error 1

**Comment by auser** [comment]
Try:

```
make
make boot
./start.sh
```

What does that say?

**Comment by auser** [comment]
I fixed this is the boot command. make boot should no longer be necessary

**Comment by santiago** [comment]
i'm having the same problem in ubuntu 9.10
i just cloned the repo so i guess i've got the last version
